# -*- coding: utf-8 -*-
"""ex10_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIwiWPwoo6ZB54nrNTPLSxM6wjLePW-g
"""

from sklearn.model_selection import train_test_split
import pandas as pd

def getTrainAndTestData(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=777)
    return X_train, X_test, y_train, y_test

# 예시 데이터 (테스트용)
X = pd.DataFrame({"feature1": [1,2,3,4,5,6,7,8,9,10],
                  "feature2": [10,9,8,7,6,5,4,3,2,1]})
y = pd.Series([0,1,0,1,0,1,0,1,0,1])

# 함수 실행
X_train, X_test, y_train, y_test = getTrainAndTestData(X, y)

print("학습용 데이터 크기:", X_train.shape, y_train.shape)
print("검증용 데이터 크기:", X_test.shape, y_test.shape)