# -*- coding: utf-8 -*-
"""ex10_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIwiWPwoo6ZB54nrNTPLSxM6wjLePW-g
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 데이터셋 로드
iris = load_iris()
X, y = iris.data, iris.target

# 이진 분류 문제로 만들기 위해 클래스가 2개인 데이터만 사용
X = X[y != 2]
y = y[y != 2]

# 데이터셋 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 로지스틱 회귀 모델 생성 및 학습
model = LogisticRegression()
model.fit(X_train, y_train)

# 테스트 데이터셋에 대한 예측 및 정확도 계산
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("정확도:", accuracy)