# -*- coding: utf-8 -*-
"""ex10_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIwiWPwoo6ZB54nrNTPLSxM6wjLePW-g
"""

!wget https://raw.githubusercontent.com/sharmaroshan/Heart-UCI-Dataset/master/heart.csv -O heart.csv

import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv("heart.csv")
x_train, x_test = train_test_split(df, test_size=0.2, random_state=777)

print("학습용 데이터 크기:", x_train.shape)
print("테스트용 데이터 크기:", x_test.shape)

