# -*- coding: utf-8 -*-
"""ex8_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxTMOWhQy4scK2N8NC7wqYPhOjOCgOFh
"""

data =[80, 90, 50, 100, 70, 60]
import numpy
std = numpy.std(data)
print("표준편차=",std)