# -*- coding: utf-8 -*-
"""ex8_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Phbekfq8UQ-HsBsZtyjYr1QIpYGwpkO
"""

data =[80, 90, 50, 100, 70, 60]
import numpy
mean = numpy.mean(data)
print("평균=",mean)