# -*- coding: utf-8 -*-
"""ex12_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIwiWPwoo6ZB54nrNTPLSxM6wjLePW-g
"""

import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

# 사인파 데이터 생성
x = np.linspace(0, 100, 1000)
y = np.sin(x)

# 시퀀스 데이터 준비
n_steps = 10
X, y_seq = [], []
for i in range(len(y) - n_steps):
    X.append(y[i:i + n_steps])
    y_seq.append(y[i + n_steps])
X, y_seq = np.array(X), np.array(y_seq)
X = X.reshape((X.shape[0], X.shape[1], 1))

# 모델 구축 및 훈련
model = Sequential()
model.add(SimpleRNN(50, activation='relu', input_shape=(n_steps, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(X, y_seq, epochs=100, verbose=0)

# 다음 시점 값 예측
last_sequence = X[-1:]  # 마지막 10개 데이터
predicted_value = model.predict(last_sequence)
print(f"예측된 다음 시점의 값: {predicted_value[0][0]}")