# -*- coding: utf-8 -*-
"""ex12_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIwiWPwoo6ZB54nrNTPLSxM6wjLePW-g
"""

import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM, GRU

# 사인파 데이터 생성
x = np.linspace(0, 100, 1000)
y = np.sin(x)

# 시퀀스 데이터 준비
n_steps = 10
X, y_seq = [], []
for i in range(len(y) - n_steps):
    X.append(y[i:i + n_steps])
    y_seq.append(y[i + n_steps])
X, y_seq = np.array(X), np.array(y_seq)
X = X.reshape((X.shape[0], X.shape[1], 1))

# ------------------------
# ① SimpleRNN 모델
# ------------------------
rnn_model = Sequential()
rnn_model.add(SimpleRNN(50, activation='relu', input_shape=(n_steps, 1)))
rnn_model.add(Dense(1))
rnn_model.compile(optimizer='adam', loss='mean_squared_error')
rnn_model.fit(X, y_seq, epochs=100, verbose=0)

rnn_pred = rnn_model.predict(X[-1:], verbose=0)
print(f"SimpleRNN 예측된 다음 시점의 값: {rnn_pred[0][0]}")

# ------------------------
# ② LSTM 모델
# ------------------------
lstm_model = Sequential()
lstm_model.add(LSTM(50, activation='relu', input_shape=(n_steps, 1)))
lstm_model.add(Dense(1))
lstm_model.compile(optimizer='adam', loss='mean_squared_error')
lstm_model.fit(X, y_seq, epochs=100, verbose=0)

lstm_pred = lstm_model.predict(X[-1:], verbose=0)
print(f"LSTM 예측된 다음 시점의 값: {lstm_pred[0][0]}")

# ------------------------
# ③ GRU 모델
# ------------------------
gru_model = Sequential()
gru_model.add(GRU(50, activation='relu', input_shape=(n_steps, 1)))
gru_model.add(Dense(1))
gru_model.compile(optimizer='adam', loss='mean_squared_error')
gru_model.fit(X, y_seq, epochs=100, verbose=0)

gru_pred = gru_model.predict(X[-1:], verbose=0)
print(f"GRU 예측된 다음 시점의 값: {gru_pred[0][0]}")