# -*- coding: utf-8 -*-
"""ex12_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIwiWPwoo6ZB54nrNTPLSxM6wjLePW-g
"""

import numpy as np

def getMAPE(y_test, y_pred):
    return np.mean(np.abs((y_test - y_pred) / y_test)) * 100

#사용예시
y_test = np.array([100, 200, 300])
y_pred = np.array([110, 190, 290])

mape = getMAPE(y_test, y_pred)
print(f"MAPE: {mape:.2f}%")