# -*- coding: utf-8 -*-
"""ex9_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIwiWPwoo6ZB54nrNTPLSxM6wjLePW-g
"""

import pandas as pd
x = [80, 50, 70]
y = [90, 100, 60]
df = pd.DataFrame({"math": x, "english": y})
coef = df.corr(method = 'kendall')

print(coef)